### ISSUE TITLE
v2024.3.3b4 (Windows): Errror 'Installation not complete'

### ISSUE THREAD

**Issue by UselessGuru** [TrailingStop/TT-Miner-beta#11]
`Bin\TTMiner-v2024.3.3b4\TT-Miner.exe -c KIIRO -o ssl://firopow.eu.mine.zergpool.com:13001 -u ########################### -p c=BTC,mc=KIIRO,ID=################ -report-average 5 -report-interval 5 -daginfo -b 127.0.0.1:4001 -d 0`
17:21:59.913 ********* TT-Miner - Version: 2024.3.3 - Beta 4 (Jul 23 2024 17:53:31)
17:21:59.913 ********* Log system initialized...
17:21:59.913 ********* Internal event system initialized...
17:21:59.913 ********* Worker threads initialized, using 2 threads...
17:21:59.929 ********* Commandline: Bin\TTMiner-v2024.3.3b4\TT-Miner.exe -c KIIRO -o ssl://firopow.eu.mine.zergpool.com:13001 -u ################## -p c=BTC,mc=KIIRO,ID=############# -report-average 5 -report-interval 5 -daginfo -b 127.0.0.1:4001 -d 0
**17:22:01.562 Installation not complete.**
17:22:01.593 ********* Stop worker threads...
17:22:01.593 ********* Internal event system stopped and destroyed...
17:22:01.593 ********* All threads stopped and destroyed...

![image](https://github.com/user-attachments/assets/e54eb9cf-78ea-43c5-a401-b0b9cee9da60)

**Comment by TrailingStop** [comment]
hi - can you please check the windows system eventlog if there is any entry TT related. seems like TT cannot load all dll's.

**Comment by UselessGuru** [comment]
No event log entries. I tested on 2 pc's. Same error.
2024.3.3b1 runs just fine.

**Comment by TrailingStop** [comment]
yes. i added a function that tries to load each algo since some users have issues to get them into memory. same on your box - seems to me that some algos cannot load. let me add some more details to the message

**Comment by TrailingStop** [comment]
Hi, can you please replace the exe with the attached one? It prints some more infoprmation.
[TT-Miner.zip](https://github.com/user-attachments/files/16364791/TT-Miner.zip)

**Comment by UselessGuru** [comment]
Nope, No extra messages in the test version.
Is there a way to increase output level?

**Comment by TrailingStop** [comment]
Hi - are you sure? you should see something like this, right after start of TT:

Selected devices ****** begin:
Device id: 1
Device platform: 2
Device chip: 1
Selected devices ****** end
add (DEF) ms: 1
m_arrayMiningOptionsAlgoPtr.size: 1
m_arrayMiningOptionsAlgoPtr-size: 1
m_arrayMiningOptionsAlgoPtr-coinname: Spectre
m_arrayMiningOptionsAlgoPtr-vectorAlgoPlugin.size: 1
vectorAlgoPlugin.name: SpectreX
l_iAlgoPlugin.pPlugin->ui32AlgoPlatform: 00000006
p_ePlatform: 00000002
Selected devices ****** after platfrom select begin:
Device id: 1

**Comment by UselessGuru** [comment]
No. Same as before:

18:10:55.203 ********* TT-Miner - Version: 2024.3.3 - Beta 4 (Jul 23 2024 17:53:31)
18:10:55.203 ********* Log system initialized...
18:10:55.203 ********* Internal event system initialized...
18:10:55.203 ********* Worker threads initialized, using 2 threads...
18:10:55.219 ********* Commandline: TT-Miner.exe -c KIIRO -o ssl://firopow.eu.mine.zergpool.com:13001 -u ################ -p c=BTC,mc=KIIRO,ID=######### -report-average 5 -report-interval 5 -daginfo -b 127.0.0.1:4005 -d 3
18:10:56.691 Installation not complete.
18:10:56.691 ********* Stop worker threads...
18:10:56.691 ********* Internal event system stopped and destroyed...
18:10:56.691 ********* All threads stopped and destroyed...

**Comment by TrailingStop** [comment]
it should say beta 5:
18:13:32.524 ********* TT-Miner - Version: 2024.3.3 - Beta 5 (Jul 24 2024 18:07:07)

**Comment by UselessGuru** [comment]
Sorry. My bad.

18:17:57.774 ********* TT-Miner - Version: 2024.3.3 - Beta 5 (Jul 24 2024 18:07:07)
18:17:57.774 ********* Log system initialized...
18:17:57.774 ********* Internal event system initialized...
18:17:57.774 ********* Worker threads initialized, using 2 threads...
18:17:57.805 ********* Commandline: TT-Miner.exe -c KIIRO -o ssl://firopow.eu.mine.zergpool.com:13001 -u ############## -p c=BTC,mc=KIIRO,ID=############ -report-average 5 -report-interval 5 -daginfo -b 127.0.0.1:4005 -d 3
Selected devices ****** begin:
Device id: 3
Device platform: 4
Device chip: 2
Selected devices ****** end
add (DEF) ms: 1
m_arrayMiningOptionsAlgoPtr.size: 1
m_arrayMiningOptionsAlgoPtr-size: 1
m_arrayMiningOptionsAlgoPtr-coinname: KiiroCoin
m_arrayMiningOptionsAlgoPtr-vectorAlgoPlugin.size: 1
vectorAlgoPlugin.name: ProgPoW
l_iAlgoPlugin.pPlugin->ui32AlgoPlatform: 00000006
p_ePlatform: 00000004
Selected devices ****** after platfrom select begin:
Device id: 3
Device platform: 4
Device chip: 2
Selected devices ****** after platfrom select end
Failed to load algo: EALGO_GHOSTRIDER/EDP_CPU
18:17:58.956 Installation not complete.
18:17:58.975 ********* Stop worker threads...
18:17:58.975 ********* Internal event system stopped and destroyed...
18:17:58.975 ********* All threads stopped and destroyed...

**Comment by TrailingStop** [comment]
ok - that helps a lot. thanks. will fix now.

**Comment by TrailingStop** [comment]
Can you  please 
[TT-Miner.zip](https://github.com/user-attachments/files/16365011/TT-Miner.zip)
give this another try - I suspect all the cpu algos cannot load, but need a prove.

**Comment by UselessGuru** [comment]
18:37:03.329 ********* TT-Miner - Version: 2024.3.3 - Beta 5 (Jul 24 2024 18:25:50)
18:37:03.329 ********* Log system initialized...
18:37:03.329 ********* Internal event system initialized...
18:37:03.329 ********* Worker threads initialized, using 2 threads...
Failed to load (Algos\AlgoGhostRiderCpu.dll)
The specified module could not be found.

Failed to load (Algos\AlgoSpectreXCpu.dll)
The specified module could not be found.

Failed to load (Algos\AlgoXelisCpu.dll)
The specified module could not be found.

18:37:03.347 ********* Commandline: TT-Miner.exe -c KIIRO -o ssl://firopow.eu.mine.zergpool.com:13001 -u ##############################  -p c=BTC,mc=KIIRO,ID=########### -report-average 5 -report-interval 5 -daginfo -b 127.0.0.1:4005 -d 3
Selected devices ****** begin:
Device id: 3
Device platform: 4
Device chip: 2
Selected devices ****** end
add (DEF) ms: 1
m_arrayMiningOptionsAlgoPtr.size: 1
m_arrayMiningOptionsAlgoPtr-size: 1
m_arrayMiningOptionsAlgoPtr-coinname: KiiroCoin
m_arrayMiningOptionsAlgoPtr-vectorAlgoPlugin.size: 1
vectorAlgoPlugin.name: ProgPoW
l_iAlgoPlugin.pPlugin->ui32AlgoPlatform: 00000006
p_ePlatform: 00000004
Selected devices ****** after platfrom select begin:
Device id: 3
Device platform: 4
Device chip: 2
Selected devices ****** after platfrom select end
Failed to load algo: EALGO_GHOSTRIDER/EDP_CPU
18:37:04.475 Installation not complete.
18:37:04.475 ********* Stop worker threads...
18:37:04.475 ********* Internal event system stopped and destroyed...
18:37:04.475 ********* All threads stopped and destroyed...

**Comment by TrailingStop** [comment]
Hi - i think I fixed the problem., Please try b5:
https://github.com/TrailingStop/TT-Miner-beta/releases/tag/2024.3.3-beta5

**Comment by UselessGuru** [comment]
> Please try b5:

Looking much better ;-)
Thank you!

**Comment by TrailingStop** [comment]
Thanks for testing and bug reporting
