### ISSUE TITLE
TT-Miner 2024.2.1-beta4 doesn't start with no answer on windows dual xeon e5-2680v4 rig with kylacoin

### ISSUE THREAD

**Issue by ttarelka** [TrailingStop/TT-Miner-beta#3]
TT-Miner 2024.2.1-beta4 doesn't start with no answer on windows dual xeon e5-2680v4 rig with kylacoin "tt-miner.exe -a flex -P miner_walle.1@stratum+tcp://ru.vipor.net:5120"

**Comment by TrailingStop** [comment]
Hi, i think you use the wrong pool. kyla on vipor is either:
tcp: ru.vipor.net:5025
or
ssl: ru.vipor.net:5125

so if you want to use tcp use this line:
tt-miner.exe -a flex -P miner_walle.1@ru.vipor.net:5025
