### ISSUE TITLE
gpu disable 

### ISSUE THREAD

**Issue by Ob0ne30** [TrailingStop/TT-Miner-beta#5]
is there a command to disable gpu, so i can use on different miner

**Comment by TrailingStop** [comment]
you should be able to use different miner. TT loads just a context.  But for that a fix is coming.

**Comment by Ob0ne30** [comment]
Thank you it was on 2 rigs, switch them over an the gpu never started reboot didnt fix. thought id reach out.

**Comment by TrailingStop** [comment]
Hi, please try beta 5. It comes with a fix for this. Let me know if it works for you now as expected.
Thanks
