### ISSUE TITLE
Question about hiveos version TT version 2024.2.1 Beta 5-2

### ISSUE THREAD

**Issue by niels-sys** [TrailingStop/TT-Miner-beta#9]
Hi is it possible that the wrong binary is packed in this tar.gz file? 
https://github.com/TrailingStop/TT-Miner-beta/releases/download/2024.2.1-beta5/TT-Miner-2024.2.1B5.2.Hive.tar.gz

When downloaded and installed in hiveos keep getting this version "TT-Miner - Version: 2024.2.1 - Beta 5"which is expired?
Also after manual replacing the binary from a separate download in hiveos:

15:37:36.950 ********* TT-Miner - Version: 2024.2.1 - Beta 5 (Jun  9 2024 10:58:52)
15:37:36.950 ********* NO DEVFEE!
15:37:36.950 ********* Log system initialized...
15:37:36.950 Beta 5 test period expired - please check for a new version of TT-Miner.

Thanks!

**Comment by TrailingStop** [comment]
Hi - sorry for my late reply - please use latest release version.
